# Use a imagem base
FROM alpine:latest

# Cria um diretório no contêiner
RUN mkdir /app

# Define o diretório de trabalho
WORKDIR /app

# Define o volume para o diretório
VOLUME /app

# Define o comando a ser executado quando o contêiner for iniciado
CMD ["sleep", "infinity"]
